Rails.application.routes.draw do
  
  root 'account#login'
  resources :account
  resources :sessions, only: [:new, :create, :destroy]
  get 'current_user', to: 'sessions#current_user', as:'current_user'
  get 'account_auth', to: 'account#auth'
  post 'account_auth', to: 'account#auth'
  get 'account_create', to: 'account#create'
  post 'account_create', to: 'account#create'
  get 'account_menu', to: 'menu#menu', as: 'menu'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'account_menu/gmap', to:'gmap#map', as: 'gmap'
  post 'account_menu/gmap/search', to:'gmap#results', as: 'gmap_search'
  get 'account_menu/gmap/search', to:'gmap#map'
  get 'account_menu/chats', to:'chat#index'
  get 'account_menu/chat/new', to:'chat#new'
  post 'account_menu/chat/new', to:'chat#create'
  get 'account_menu/chat/:title', to:'chat#show'
  post 'account_menu/chat/:title', to:'chat#show', as:'showchat'
  post 'account_menu/chat/:title/reply=new', to:'chat#reply', as:'chatreply'
  get 'account_menu/chat/:title/reply=new', to:'chat#reply'
  post 'account_menu/chat/:title/reply=submit', to:'chat#submit', as:'submitreply'
  post 'account_menu/chat/:title/participants', to:'chat#participants', as:'chatusers'
  post 'account_menu/chat/:title/participants/:name/block', to:'chat#ban', as:'chatuserblock'
  get 'account_menu/chat/:title/participants', to:'chat#participants'
  get 'account_menu/chat/:title/delete', to: 'chat#delete', as:'chatdelete'
  get 'account_menu/business', to: 'business#mybizzes', as:'selectbizz'
  get 'account_menu/business/new', to: 'business#add_biz', as:'addbizz'
  post 'account_menu/business/new', to: 'business#add_biz'
  post 'account_menu/business/:id/:name/show', to: 'business#sel_biz', as:'selbizz'
  get 'account_menu/business/:id/:name/show', to: 'business#sel_biz'
  post 'account_menu/business/edit', to: 'business#edit_biz', as:'editbiz'
  get 'account_menu/business/edit', to: 'business#edit_biz'
  post 'account_menu/business/update', to: 'business#update_biz', as:'updatebiz'
  get 'account_menu/business/update', to: 'business#update_biz'
  post 'account_menu/business/:id/delete', to: 'business#del_biz', as:'deletebiz'
  post 'account_menu/business/:id/:name/new', to:'item#new', as:'additem'
  #add route like this...
  #post 'account_menu/business/:id/items/new', to:'item#new', as:'additem'
  get 'account_menu/business/:id/:name/item/new', to:'item#new'
  post 'account_menu/business/:id/:name/item/finalize_item', to:'item#add', as:'addtobiz'
  get 'account_menu/business/:id/:name/item/finalize_item', to:'item#add'
  post 'account_menu/business/:id/:name/location', to:'gmap#single_biz_view', as:'showbiz'
  get 'account_menu/gsearch', to:'gsearch#new', as:'gsearch'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

end
